services:
  web:
    build:
      context: .
      args:
        BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}
        NEXT_PUBLIC_BETTER_AUTH_URL: ${NEXT_PUBLIC_BETTER_AUTH_URL:-http://localhost:3000}
        RP_ID: ${RP_ID:-localhost}
        AUTH_SECRET: ${AUTH_SECRET:-dev-secret}
    image: t3-better-auth:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    command: sh -c "bunx prisma migrate deploy || bunx prisma db push; bun run start -p ${PORT:-3000} -H 0.0.0.0"
    # Persist SQLite DB file if using sqlite
    volumes:
      - ./prisma:/app/prisma
    restart: unless-stopped

