# Nixpacks configuration for T3 Better Auth App
providers = ["node"]

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NIXPACKS_NODE_PACKAGE_MANAGER = "bun"
DATABASE_URL = "file:./prisma/dev.db"
PORT = "3000"

[phases.build]
cmds = [
    "mkdir -p prisma",
    "bun run postinstall",
    "bun run db:migrate", 
    "bun run build"
]

[phases.start]
cmd = "bun run start"