import "@/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "sonner";
import { DevEmailLink } from "@/components/dev-email-link";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const headersList = await headers();
	
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body>
				<TRPCReactProvider headers={new Headers(headersList)}>{children}</TRPCReactProvider>
				<Toaster />
				<DevEmailLink />
			</body>
		</html>
	);
}
